services: 
  pg_chainlink:
    image: "postgres"
    ports: 
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - /Users/wladknd/LIB/IT/CODE/ORBEEM/orbeem-oracle/data:/var/lib/postgressql/data/
  chainlink: 
    image: "smartcontract/chainlink"
    env_file: 
      - .env
    depends_on:
      - pg_chainlink
    ports: 
      - "6688:6688"
    volumes:
      - /Users/wladknd/LIB/IT/CODE/ORBEEM/orbeem-oracle/chainlink-data:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/credentials.txt